services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kana-flashcard-app-build
    image: kana-flashcard-app:build
    environment:
      - NODE_ENV=production

  db:
    extends:
      file: docker-compose.yml
      service: db
    container_name: kana-flashcard-db-build
    user: "0:0"
    read_only: false
    cap_drop: []
    cap_add:
      - ALL
    volumes:
      - postgres_data_build:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kana-flashcard-pgadmin-build
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data_build:/var/lib/pgadmin
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    # Production-ready security settings that allow pgAdmin to function
    user: "0:0"
    read_only: false
    security_opt: []
    cap_drop: []
    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
    tmpfs:
      - /tmp
      - /var/run/pgadmin
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  postgres_data_build:
  pgadmin_data_build:

networks:
  app-network:
    driver: bridge