name: E2E Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Setup environment
        run: |
          cat > .env << EOF
          POSTGRES_PRISMA_URL=postgresql://postgres:postgres@localhost:5432/postgres
          POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@localhost:5432/postgres
          AUTH_URL=http://localhost:3000
          AUTH_SECRET=test-secret-for-ci
          NODE_ENV=test
          EOF

      - name: Setup database
        run: |
          pnpm exec prisma generate
          pnpm exec prisma migrate deploy
          pnpm exec prisma db seed

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
